version: "2"
run:
  # Linting uses a lot of memory. Keep it under control by only running a single
  # worker.
  concurrency: 1
linters:

  # Specify an enabled list of linters rather than a disabled list because
  # the latest linter includes many sub-linters which do not pass the codebase.
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: internal/test
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      # simplify code: gofmt with `-s` option, true by default
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
