package aperture

import (
	"context"
	"crypto/tls"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"net"
	"net/http"
	_ "net/http/pprof" // Blank import to set up profiling HTTP handlers.
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/goccy/go-yaml"
	grpc_prometheus "github.com/grpc-ecosystem/go-grpc-prometheus"
	gateway "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	flags "github.com/jessevdk/go-flags"
	"github.com/lightninglabs/aperture/admin"
	"github.com/lightninglabs/aperture/adminrpc"
	"github.com/lightninglabs/aperture/aperturedb"
	"github.com/lightninglabs/aperture/auth"
	"github.com/lightninglabs/aperture/challenger"
	"github.com/lightninglabs/aperture/lnc"
	"github.com/lightninglabs/aperture/mint"
	"github.com/lightninglabs/aperture/proxy"
	"github.com/lightninglabs/lightning-node-connect/hashmailrpc"
	"github.com/lightninglabs/lndclient"
	"github.com/lightningnetwork/lnd"
	"github.com/lightningnetwork/lnd/build"
	"github.com/lightningnetwork/lnd/cert"
	"github.com/lightningnetwork/lnd/lnrpc"
	"github.com/lightningnetwork/lnd/lntypes"
	"github.com/lightningnetwork/lnd/signal"
	"github.com/lightningnetwork/lnd/tor"
	clientv3 "go.etcd.io/etcd/client/v3"
	"golang.org/x/crypto/acme/autocert"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/keepalive"
	"google.golang.org/protobuf/encoding/protojson"
)

const (
	// topLevelKey is the top level key for an etcd cluster where we'll
	// store all L402 proxy related data.
	topLevelKey = "lsat/proxy"

	// etcdKeyDelimeter is the delimeter we'll use for all etcd keys to
	// represent a path-like structure.
	etcdKeyDelimeter = "/"

	// selfSignedCertOrganization is the static string that we encode in the
	// organization field of a certificate if we create it ourselves.
	selfSignedCertOrganization = "aperture autogenerated cert"

	// selfSignedCertValidity is the certificate validity duration we are
	// using for aperture certificates. This is higher than lnd's default
	// 14 months and is set to a maximum just below what some operating
	// systems set as a sane maximum certificate duration. See
	// https://support.apple.com/en-us/HT210176 for more information.
	selfSignedCertValidity = time.Hour * 24 * 820

	// selfSignedCertExpiryMargin is how much time before the certificate's
	// expiry date we already refresh it with a new one. We set this to half
	// the certificate validity length to make the chances bigger for it to
	// be refreshed on a routine server restart.
	selfSignedCertExpiryMargin = selfSignedCertValidity / 2

	// hashMailGRPCPrefix is the prefix a gRPC request URI has when it is
	// meant for the hashmailrpc server to be handled.
	hashMailGRPCPrefix = "/hashmailrpc.HashMail/"

	// hashMailRESTPrefix is the prefix a REST request URI has when it is
	// meant for the hashmailrpc server to be handled.
	hashMailRESTPrefix = "/v1/lightning-node-connect/hashmail"

	// adminGRPCPrefix is the prefix a gRPC request URI has when it is
	// meant for the admin server to be handled.
	adminGRPCPrefix = "/adminrpc.Admin/"

	// adminRESTPrefix is the prefix a REST request URI has when it is
	// meant for the admin REST API to be handled.
	adminRESTPrefix = "/api/admin/"

	// defaultAdminMacaroonFilename is the default filename for the admin
	// macaroon.
	defaultAdminMacaroonFilename = "admin.macaroon"

	// invoiceMacaroonName is the name of the invoice macaroon belonging
	// to the target lnd node.
	invoiceMacaroonName = "invoice.macaroon"

	// defaultMailboxAddress is the default address of the mailbox server
	// that will be used if none is specified.
	defaultMailboxAddress = "mailbox.terminal.lightning.today:443"
)

var (
	// http2TLSCipherSuites is the list of cipher suites we allow the server
	// to use. This list removes a CBC cipher from the list used in lnd's
	// cert package because the underlying HTTP/2 library treats it as a bad
	// cipher, according to https://tools.ietf.org/html/rfc7540#appendix-A
	// (also see golang.org/x/net/http2/ciphers.go).
	http2TLSCipherSuites = []uint16{
		tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
		tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
		tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
		tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,
	}

	// clientStreamingURIs is the list of REST URIs that are
	// client-streaming and shouldn't be closed after a single message.
	clientStreamingURIs = []*regexp.Regexp{
		regexp.MustCompile("^/v1/lightning-node-connect/hashmail/send$"),
	}
)

// Main is the true entrypoint of Aperture.
func Main() {
	// TODO: Prevent from running twice.
	err := run()

	// Unwrap our error and check whether help was requested from our flag
	// library. If the error is not wrapped, Unwrap returns nil. It is
	// still safe to check the type of this nil error.
	flagErr, isFlagErr := errors.Unwrap(err).(*flags.Error)
	isHelpErr := isFlagErr && flagErr.Type == flags.ErrHelp

	// If we got a nil error, or help was requested, just exit.
	if err == nil || isHelpErr {
		os.Exit(0)
	}

	// Print any other non-help related errors.
	_, _ = fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

// run sets up the proxy server and runs it. This function blocks until a
// shutdown signal is received.
func run() error {
	// Before starting everything, make sure we can intercept any interrupt
	// signals so we can block on waiting for them later.
	interceptor, err := signal.Intercept()
	if err != nil {
		return err
	}

	// Next, parse configuration file and set up logging.
	cfg, err := getConfig()
	if err != nil {
		return fmt.Errorf("unable to parse config file: %w", err)
	}
	err = setupLogging(cfg, interceptor)
	if err != nil {
		return fmt.Errorf("unable to set up logging: %v", err)
	}

	errChan := make(chan error)
	a := NewAperture(cfg)
	if err := a.Start(errChan, interceptor.ShutdownChannel()); err != nil {
		return fmt.Errorf("unable to start aperture: %v", err)
	}

	select {
	case <-interceptor.ShutdownChannel():
		log.Infof("Received interrupt signal, shutting down aperture.")

	case err := <-errChan:
		log.Errorf("Error while running aperture: %v", err)
	}

	return a.Stop()
}

// Aperture is the main type of the aperture service. It holds all components
// that are required for the authenticating reverse proxy to do its job.
type Aperture struct {
	cfg *Config

	etcdClient    *clientv3.Client
	db            *sql.DB
	challenger    challenger.Challenger
	httpsServer   *http.Server
	torHTTPServer *http.Server
	proxy         *proxy.Proxy
	proxyCleanup  func()
	adminCleanup  func()

	wg   sync.WaitGroup
	quit chan struct{}
}

// NewAperture creates a new instance of the Aperture service.
func NewAperture(cfg *Config) *Aperture {
	return &Aperture{
		cfg:  cfg,
		quit: make(chan struct{}),
	}
}

// Start sets up the proxy server and starts it.
//
//nolint:gocyclo
func (a *Aperture) Start(errChan chan error, shutdown <-chan struct{}) error {
	// Start the prometheus exporter.
	err := StartPrometheusExporter(a.cfg.Prometheus, shutdown)
	if err != nil {
		return fmt.Errorf("unable to start the prometheus "+
			"exporter: %v", err)
	}

	// Enable http profiling and validate profile port number if requested.
	if a.cfg.Profile != 0 {
		if a.cfg.Profile < 1024 {
			return fmt.Errorf("the profile port must be between " +
				"1024 and 65535")
		}

		go func() {
			http.Handle("/", http.RedirectHandler(
				"/debug/pprof", http.StatusSeeOther,
			))

			listenAddr := fmt.Sprintf("localhost:%d", a.cfg.Profile)

			log.Infof("Starting profile server at %s", listenAddr)
			fmt.Println(http.ListenAndServe(listenAddr, nil))
		}()
	}

	var (
		secretStore mint.SecretStore
		onionStore  tor.OnionStore
		lncStore    lnc.Store
		txnStore    *aperturedb.L402TransactionsStore
		svcStore    *aperturedb.ServicesStore
	)

	// Connect to the chosen database backend.
	switch a.cfg.DatabaseBackend {
	case "etcd":
		// Initialize our etcd client.
		a.etcdClient, err = clientv3.New(clientv3.Config{
			Endpoints:   []string{a.cfg.Etcd.Host},
			DialTimeout: 5 * time.Second,
			Username:    a.cfg.Etcd.User,
			Password:    a.cfg.Etcd.Password,
		})
		if err != nil {
			return fmt.Errorf("unable to connect to etcd: %v", err)
		}

		secretStore = newSecretStore(a.etcdClient)
		onionStore = newOnionStore(a.etcdClient)

	case "postgres":
		db, err := aperturedb.NewPostgresStore(a.cfg.Postgres)
		if err != nil {
			return fmt.Errorf("unable to connect to postgres: %v",
				err)
		}
		a.db = db.DB
		secretStore, onionStore, lncStore, txnStore, svcStore =
			initSQLStores(db.BaseDB)

	case "sqlite":
		db, err := aperturedb.NewSqliteStore(a.cfg.Sqlite)
		if err != nil {
			return fmt.Errorf("unable to connect to sqlite: %v",
				err)
		}
		a.db = db.DB
		secretStore, onionStore, lncStore, txnStore, svcStore =
			initSQLStores(db.BaseDB)

	default:
		return fmt.Errorf("unknown database backend: %s",
			a.cfg.DatabaseBackend)
	}

	log.Infof("Using %v as database backend", a.cfg.DatabaseBackend)

	// Only enable settlement tracking when the admin API is enabled.
	// This avoids the startup cost of reconciling historical invoices
	// for operators that don't use the admin dashboard.
	var challengerOpts []challenger.LndChallengerOption
	if a.cfg.Admin != nil && a.cfg.Admin.Enabled {
		challengerOpts = buildChallengerOpts(txnStore)
	}

	if !a.cfg.Authenticator.Disable {
		authCfg := a.cfg.Authenticator
		genInvoiceReq := func(price int64) (*lnrpc.Invoice, error) {
			return &lnrpc.Invoice{
				Memo:  "L402",
				Value: price,
			}, nil
		}

		switch {
		case authCfg.Passphrase != "":
			log.Infof("Using lnc's authenticator config")

			if a.cfg.DatabaseBackend == "etcd" {
				return fmt.Errorf("etcd is not supported as " +
					"a database backend for lnc " +
					"connections")
			}

			session, err := lnc.NewSession(
				authCfg.Passphrase, authCfg.MailboxAddress,
				authCfg.DevServer,
			)
			if err != nil {
				return fmt.Errorf("unable to create lnc "+
					"session: %w", err)
			}

			a.challenger, err = challenger.NewLNCChallenger(
				session, lncStore, a.cfg.InvoiceBatchSize,
				genInvoiceReq, errChan, a.cfg.StrictVerify,
				challengerOpts...,
			)
			if err != nil {
				return fmt.Errorf("unable to start lnc "+
					"challenger: %w", err)
			}

		case authCfg.LndHost != "":
			log.Infof("Using lnd's authenticator config")

			authCfg := a.cfg.Authenticator
			client, err := lndclient.NewBasicClient(
				authCfg.LndHost, authCfg.TLSPath,
				authCfg.MacDir, authCfg.Network,
				lndclient.MacFilename(
					invoiceMacaroonName,
				),
			)
			if err != nil {
				return err
			}

			a.challenger, err = challenger.NewLndChallenger(
				client, a.cfg.InvoiceBatchSize, genInvoiceReq,
				context.Background, errChan, a.cfg.StrictVerify,
				challengerOpts...,
			)
			if err != nil {
				return err
			}
		}
	}

	// Load persisted services from the database and merge with config
	// file services. DB services take precedence (by name) over config
	// file services so that runtime changes survive restarts.
	initialServices := mergeServicesFromDB(a.cfg.Services, svcStore)

	// Create a synchronized services holder so the admin server can
	// safely read and update the service list concurrently with the
	// proxy.
	svcHolder := &serviceHolder{services: initialServices}
	adminPriority, adminFallback, adminCleanup, err :=
		createAdminServer(
			a.cfg, txnStore, secretStore, svcStore,
			svcHolder.get,
			func(s []*proxy.Service) error {
				if err := a.UpdateServices(s); err != nil {
					return err
				}
				svcHolder.set(s)
				return nil
			},
		)
	if err != nil {
		return err
	}
	a.adminCleanup = adminCleanup

	// Create the proxy and connect it to lnd.
	mintTxnStore := asMintTransactionStore(txnStore)
	a.proxy, a.proxyCleanup, err = createProxy(
		a.cfg, a.challenger, secretStore, mintTxnStore,
		adminPriority, adminFallback,
	)
	if err != nil {
		return err
	}
	handler := http.HandlerFunc(a.proxy.ServeHTTP)
	a.httpsServer = &http.Server{
		Addr:         a.cfg.ListenAddr,
		Handler:      handler,
		IdleTimeout:  a.cfg.IdleTimeout,
		ReadTimeout:  a.cfg.ReadTimeout,
		WriteTimeout: a.cfg.WriteTimeout,
	}

	log.Infof("Creating server with idle_timeout=%v, read_timeout=%v "+
		"and write_timeout=%v", a.cfg.IdleTimeout, a.cfg.ReadTimeout,
		a.cfg.WriteTimeout)

	// Create TLS configuration by either creating new self-signed certs or
	// trying to obtain one through Let's Encrypt.
	var serveFn func() error
	if a.cfg.Insecure {
		// Normally, HTTP/2 only works with TLS. But there is a special
		// version called HTTP/2 Cleartext (h2c) that some clients
		// support and that gRPC uses when the grpc.WithInsecure()
		// option is used. The default HTTP handler doesn't support it
		// though so we need to add a special h2c handler here.
		serveFn = a.httpsServer.ListenAndServe
		a.httpsServer.Handler = h2c.NewHandler(handler, &http2.Server{})
	} else {
		a.httpsServer.TLSConfig, err = getTLSConfig(
			a.cfg.ServerName, a.cfg.BaseDir, a.cfg.AutoCert,
		)
		if err != nil {
			return err
		}
		serveFn = func() error {
			// The httpsServer.TLSConfig contains certificates at
			// this point so we don't need to pass in certificate
			// and key file names.
			return a.httpsServer.ListenAndServeTLS("", "")
		}
	}

	// Finally run the server.
	log.Infof("Starting the server, listening on %s.", a.cfg.ListenAddr)

	a.wg.Add(1)
	go func() {
		defer a.wg.Done()

		select {
		case errChan <- serveFn():
		case <-a.quit:
		}
	}()

	// If we need to listen over Tor as well, we'll set up the onion
	// services now. We're not able to use TLS for onion services since they
	// can't be verified, so we'll spin up an additional HTTP/2 server
	// _without_ TLS that is not exposed to the outside world. This server
	// will only be reached through the onion services, which already
	// provide encryption, so running this additional HTTP server should be
	// relatively safe.
	if a.cfg.Tor.V3 {
		torController, err := initTorListener(a.cfg, onionStore)
		if err != nil {
			return err
		}
		defer func() {
			_ = torController.Stop()
		}()

		a.torHTTPServer = &http.Server{
			Addr:    fmt.Sprintf("localhost:%d", a.cfg.Tor.ListenPort),
			Handler: h2c.NewHandler(handler, &http2.Server{}),
		}
		a.wg.Add(1)
		go func() {
			defer a.wg.Done()

			select {
			case errChan <- a.torHTTPServer.ListenAndServe():
			case <-a.quit:
			}
		}()
	}

	return nil
}

// serviceHolder provides synchronized access to the service list so the admin
// server and proxy can safely read/update services concurrently.
type serviceHolder struct {
	mu       sync.Mutex
	services []*proxy.Service
}

func (h *serviceHolder) get() []*proxy.Service {
	h.mu.Lock()
	defer h.mu.Unlock()

	// Return a copy of the slice so callers can safely mutate it.
	cpy := make([]*proxy.Service, len(h.services))
	copy(cpy, h.services)
	return cpy
}

func (h *serviceHolder) set(services []*proxy.Service) {
	h.mu.Lock()
	defer h.mu.Unlock()

	h.services = services
}

// UpdateServices instructs the proxy to re-initialize its internal
// configuration of backend services. This can be used to add or remove backends
// at run time or enable/disable authentication on the fly.
func (a *Aperture) UpdateServices(services []*proxy.Service) error {
	return a.proxy.UpdateServices(services)
}

// Stop gracefully shuts down the Aperture service.
func (a *Aperture) Stop() error {
	var returnErr error

	if a.challenger != nil {
		a.challenger.Stop()
	}

	// Stop admin server resources.
	if a.adminCleanup != nil {
		a.adminCleanup()
	}

	// Stop everything that was started alongside the proxy, for example the
	// gRPC and REST servers.
	if a.proxyCleanup != nil {
		a.proxyCleanup()
	}

	if a.etcdClient != nil {
		if err := a.etcdClient.Close(); err != nil {
			log.Errorf("Error terminating etcd client: %v", err)
			returnErr = err
		}
	}

	if a.db != nil {
		if err := a.db.Close(); err != nil {
			log.Errorf("Error closing database: %v", err)
			returnErr = err
		}
	}

	// Shut down our client and server connections now. This should cause
	// the first goroutine to quit.
	cleanup(a.httpsServer, a.proxy)

	// If we started a tor server as well, shut it down now too to cause the
	// second goroutine to quit.
	if a.torHTTPServer != nil {
		if err := a.torHTTPServer.Close(); err != nil {
			log.Errorf("Error stopping tor server: %v", err)
			returnErr = err
		}
	}

	// Now we wait for the goroutines to exit before we return. The defers
	// will take care of the rest of our started resources.
	close(a.quit)
	a.wg.Wait()

	return returnErr
}

// fileExists reports whether the named file or directory exists.
// This function is taken from https://github.com/btcsuite/btcd
func fileExists(name string) bool {
	if _, err := os.Stat(name); err != nil {
		if os.IsNotExist(err) {
			return false
		}
	}
	return true
}

// getConfig loads and parses the configuration file then checks it for valid
// content.
func getConfig() (*Config, error) {
	// Pre-parse command line flags to determine whether we've been pointed
	// to a custom config file.
	cfg := NewConfig()
	if _, err := flags.Parse(cfg); err != nil {
		return nil, err
	}

	// If a custom config file is provided, we require that it exists.
	var mustExist bool

	// Start with our default path for config file.
	configFile := filepath.Join(apertureDataDir, defaultConfigFilename)

	// If a base directory is set, we'll look in there for a config file.
	// We don't require it to exist because we could just want to place
	// all of our files here, and specify all config inline.
	if cfg.BaseDir != "" {
		configFile = filepath.Join(cfg.BaseDir, defaultConfigFilename)
	}

	// If a specific config file is set, we'll look here for a config file,
	// even if a base directory for our files was set. In this case, the
	// config file must exist, since we're specifically being pointed it.
	if cfg.ConfigFile != "" {
		configFile = lnd.CleanAndExpandPath(cfg.ConfigFile)
		mustExist = true
	}

	// Read our config file, either from the custom path provided or our
	// default location.
	b, err := os.ReadFile(configFile)
	switch {
	// If the file was found, unmarshal it.
	case err == nil:
		err = yaml.Unmarshal(b, cfg)
		if err != nil {
			return nil, err
		}

	// If the error is unrelated to the existence of the file, we must
	// always return it.
	case !os.IsNotExist(err):
		return nil, err

	// If we require that the config file exists and we got an error
	// related to file existence, we must fail.
	case mustExist && os.IsNotExist(err):
		return nil, fmt.Errorf("config file: %v must exist: %w",
			configFile, err)
	}

	// Finally, parse the remaining command line options again to ensure
	// they take precedence.
	if _, err := flags.Parse(cfg); err != nil {
		return nil, err
	}

	// Clean and expand our base dir, cert and macaroon paths.
	cfg.BaseDir = lnd.CleanAndExpandPath(cfg.BaseDir)
	cfg.Authenticator.TLSPath = lnd.CleanAndExpandPath(
		cfg.Authenticator.TLSPath,
	)
	cfg.Authenticator.MacDir = lnd.CleanAndExpandPath(
		cfg.Authenticator.MacDir,
	)

	// Set default mailbox address if none is set.
	if cfg.Authenticator.MailboxAddress == "" {
		cfg.Authenticator.MailboxAddress = defaultMailboxAddress
	}

	// Then check the configuration that we got from the config file, all
	// required values need to be set at this point.
	if err := cfg.validate(); err != nil {
		return nil, err
	}

	return cfg, nil
}

// setupLogging parses the debug level and initializes the log file rotator.
func setupLogging(cfg *Config, interceptor signal.Interceptor) error {
	if cfg.DebugLevel == "" {
		cfg.DebugLevel = defaultLogLevel
	}

	// Now initialize the logger and set the log level.
	sugLogMgr := build.NewSubLoggerManager(
		build.NewDefaultLogHandlers(cfg.Logging, logWriter)...,
	)
	SetupLoggers(sugLogMgr, interceptor)

	// Use our default data dir unless a base dir is set.
	logFile := filepath.Join(apertureDataDir, defaultLogFilename)
	if cfg.BaseDir != "" {
		logFile = filepath.Join(cfg.BaseDir, defaultLogFilename)
	}

	err := logWriter.InitLogRotator(
		cfg.Logging.File, logFile,
	)
	if err != nil {
		return err
	}

	return build.ParseAndSetDebugLevels(cfg.DebugLevel, sugLogMgr)
}

// getTLSConfig returns a TLS configuration for either a self-signed certificate
// or one obtained through Let's Encrypt.
func getTLSConfig(serverName, baseDir string, autoCert bool) (
	*tls.Config, error) {

	// Use our default data dir unless a base dir is set.
	apertureDir := apertureDataDir
	if baseDir != "" {
		apertureDir = baseDir
	}

	// If requested, use the autocert library that will create a new
	// certificate through Let's Encrypt as soon as the first client HTTP
	// request on the server using the TLS config comes in. Unfortunately
	// you cannot tell the library to create a certificate on startup for a
	// specific host.
	if autoCert {
		serverName := serverName
		if serverName == "" {
			return nil, fmt.Errorf("servername option is " +
				"required for secure operation")
		}

		certDir := filepath.Join(apertureDir, "autocert")
		log.Infof("Configuring autocert for server %v with cache dir "+
			"%v", serverName, certDir)

		manager := autocert.Manager{
			Cache:      autocert.DirCache(certDir),
			Prompt:     autocert.AcceptTOS,
			HostPolicy: autocert.HostWhitelist(serverName),
		}

		go func() {
			err := http.ListenAndServe(
				":http", manager.HTTPHandler(nil),
			)
			if err != nil {
				log.Errorf("autocert http: %v", err)
			}
		}()
		tlsCfg := manager.TLSConfig()
		tlsCfg.CipherSuites = http2TLSCipherSuites
		tlsCfg.MinVersion = tls.VersionTLS10

		return tlsCfg, nil
	}

	// If we're not using autocert, we want to create self-signed TLS certs
	// and save them at the specified location (if they don't already
	// exist).
	tlsKeyFile := filepath.Join(apertureDir, defaultTLSKeyFilename)
	tlsCertFile := filepath.Join(apertureDir, defaultTLSCertFilename)

	// Go 1.25 tightened x509 SAN validation and now rejects empty dNSName
	// entries (`x509: SAN dNSName is malformed`). When users rely on the
	// default config (no server name), we still want to generate a usable
	// self-signed cert, so we only append non-empty hostnames.
	var tlsExtraDomains []string
	if serverName != "" {
		tlsExtraDomains = append(tlsExtraDomains, serverName)
	}
	if !fileExists(tlsCertFile) && !fileExists(tlsKeyFile) {
		log.Infof("Generating TLS certificates...")
		certBytes, keyBytes, err := cert.GenCertPair(
			selfSignedCertOrganization, nil, tlsExtraDomains, false,
			selfSignedCertValidity,
		)
		if err != nil {
			return nil, err
		}

		// Now that we have the certificate and key, we'll store them
		// to the file system.
		err = cert.WriteCertPair(
			tlsCertFile, tlsKeyFile, certBytes, keyBytes,
		)
		if err != nil {
			return nil, err
		}

		log.Infof("Done generating TLS certificates")
	}

	// Load the certs now so we can inspect it and return a complete TLS
	// config later.
	certData, parsedCert, err := cert.LoadCert(tlsCertFile, tlsKeyFile)
	if err != nil {
		return nil, err
	}

	// The margin is negative, so adding it to the expiry date should give
	// us a date in about the middle of it's validity period.
	expiryWithMargin := parsedCert.NotAfter.Add(
		-1 * selfSignedCertExpiryMargin,
	)

	// We only want to renew a certificate that we created ourselves. If
	// we are using a certificate that was passed to us (perhaps created by
	// an externally running Let's Encrypt process) we aren't going to try
	// to replace it.
	isSelfSigned := len(parsedCert.Subject.Organization) > 0 &&
		parsedCert.Subject.Organization[0] == selfSignedCertOrganization

	// If the certificate expired or it was outdated, delete it and the TLS
	// key and generate a new pair.
	if isSelfSigned && time.Now().After(expiryWithMargin) {
		log.Info("TLS certificate will expire soon, generating a " +
			"new one")

		err := os.Remove(tlsCertFile)
		if err != nil {
			return nil, err
		}

		err = os.Remove(tlsKeyFile)
		if err != nil {
			return nil, err
		}

		log.Infof("Renewing TLS certificates...")
		certBytes, keyBytes, err := cert.GenCertPair(
			selfSignedCertOrganization, nil, tlsExtraDomains, false,
			selfSignedCertValidity,
		)
		if err != nil {
			return nil, err
		}

		err = cert.WriteCertPair(
			tlsCertFile, tlsKeyFile, certBytes, keyBytes,
		)
		if err != nil {
			return nil, err
		}

		log.Infof("Done renewing TLS certificates")

		// Reload the certificate data.
		certData, _, err = cert.LoadCert(tlsCertFile, tlsKeyFile)
		if err != nil {
			return nil, err
		}
	}
	return &tls.Config{
		Certificates: []tls.Certificate{certData},
		CipherSuites: http2TLSCipherSuites,
		MinVersion:   tls.VersionTLS10,
	}, nil
}

// initTorListener initiates a Tor controller instance with the Tor server
// specified in the config. Onion services will be created over which the proxy
// can be reached at.
func initTorListener(cfg *Config, store tor.OnionStore) (*tor.Controller,
	error) {

	// Establish a controller connection with the backing Tor server and
	// proceed to create the requested onion services.
	onionCfg := tor.AddOnionConfig{
		VirtualPort: int(cfg.Tor.VirtualPort),
		TargetPorts: []int{int(cfg.Tor.ListenPort)},
		Store:       store,
	}
	torController := tor.NewController(cfg.Tor.Control, "", "")
	if err := torController.Start(); err != nil {
		return nil, err
	}

	if cfg.Tor.V3 {
		onionCfg.Type = tor.V3
		addr, err := torController.AddOnion(onionCfg)
		if err != nil {
			return nil, err
		}

		log.Infof("Listening over Tor on %v", addr)
	}

	return torController, nil
}

// buildChallengerOpts builds the LndChallengerOptions. If a transaction
// store is provided, a settlement callback is added to mark transactions
// as settled when invoices are paid.
func buildChallengerOpts(
	txnStore *aperturedb.L402TransactionsStore,
) []challenger.LndChallengerOption {

	var opts []challenger.LndChallengerOption
	if txnStore != nil {
		opts = append(opts, challenger.WithSettlementCallback(
			func(hash lntypes.Hash) {
				ctx, cancel := context.WithTimeout(
					context.Background(),
					aperturedb.DefaultStoreTimeout,
				)
				defer cancel()

				err := txnStore.SettleTransaction(
					ctx, hash[:],
				)
				if err != nil {
					log.Errorf("Error settling "+
						"transaction (hash=%x): %v",
						hash[:], err)
				}
			},
		))
	}

	return opts
}

// createAdminServer creates the admin gRPC server and REST gateway following
// the same pattern as createHashMailServer. It returns two slices of local
// services: priority services (prefix-matched handlers like the gRPC, REST,
// and dashboard proxy endpoints) and fallback services (catch-all handlers
// like the dashboard static file server that should only run after proxy
// backend matching fails).
//
//nolint:gocyclo
func createAdminServer(cfg *Config,
	txnStore *aperturedb.L402TransactionsStore,
	secretStore mint.SecretStore,
	svcStore *aperturedb.ServicesStore,
	getServices func() []*proxy.Service,
	updateServices func([]*proxy.Service) error) (
	[]proxy.LocalService, []proxy.LocalService, func(), error) {

	if cfg.Admin == nil || !cfg.Admin.Enabled {
		return nil, nil, func() {}, nil
	}

	if txnStore == nil {
		log.Warnf("Admin API is enabled but the transaction store " +
			"is not available (etcd backend does not support " +
			"it). Admin API will not start.")
		return nil, nil, func() {}, nil
	}

	// Determine the admin root key. The root key is stored on disk as a
	// random 32-byte value alongside the macaroon. This avoids storing
	// the key in the shared SecretStore where its lookup hash would be
	// publicly derivable.
	macPath := cfg.Admin.MacaroonPath
	if macPath == "" {
		macPath = filepath.Join(
			apertureDataDir, defaultAdminMacaroonFilename,
		)
	}
	rootKeyPath := strings.TrimSuffix(macPath, ".macaroon") +
		".rootkey"

	rootKey, err := admin.ReadOrCreateRootKey(rootKeyPath)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("unable to initialize "+
			"admin root key: %v", err)
	}

	// Generate the admin macaroon and write it to disk only if it
	// doesn't already exist. The root key is persisted, so an existing
	// macaroon file is still valid.
	if _, statErr := os.Stat(macPath); os.IsNotExist(statErr) {
		mac, err := admin.GenerateAdminMacaroon(rootKey)
		if err != nil {
			return nil, nil, nil, fmt.Errorf("unable to generate "+
				"admin macaroon: %v", err)
		}

		if err := admin.WriteAdminMacaroon(mac, macPath); err != nil {
			return nil, nil, nil, fmt.Errorf("unable to write "+
				"admin macaroon: %v", err)
		}

		log.Infof("Admin macaroon written to %s", macPath)
	} else {
		log.Infof("Admin macaroon already exists at %s", macPath)
	}

	// Create the gRPC server with macaroon authentication.
	serverOpts := []grpc.ServerOption{
		grpc.ChainUnaryInterceptor(
			admin.MacaroonInterceptor(rootKey),
		),
		grpc.ChainStreamInterceptor(
			admin.MacaroonStreamInterceptor(rootKey),
		),
	}

	adminServer := admin.NewServer(admin.ServerConfig{
		Network:          cfg.Authenticator.Network,
		ListenAddr:       cfg.ListenAddr,
		Insecure:         cfg.Insecure,
		TransactionStore: txnStore,
		Services:         getServices,
		UpdateServices:   updateServices,
		SecretStore:      secretStore,
		ServiceStore:     svcStore,
	})

	adminGRPC := grpc.NewServer(serverOpts...)
	adminrpc.RegisterAdminServer(adminGRPC, adminServer)

	var (
		priorityServices []proxy.LocalService
		fallbackServices []proxy.LocalService
	)
	priorityServices = append(priorityServices, proxy.NewLocalService(
		adminGRPC, func(r *http.Request) bool {
			return strings.HasPrefix(
				r.URL.Path, adminGRPCPrefix,
			)
		},
	))

	// Create REST gateway.
	customMarshalerOption := gateway.WithMarshalerOption(
		gateway.MIMEWildcard, &gateway.JSONPb{
			MarshalOptions: protojson.MarshalOptions{
				UseProtoNames:   true,
				EmitUnpopulated: true,
			},
		},
	)

	ctxc, cancel := context.WithCancel(context.Background())
	cleanup := func() {
		adminGRPC.GracefulStop()
		cancel()
	}

	restProxyTLSOpt := grpc.WithTransportCredentials(
		credentials.NewTLS(
			&tls.Config{InsecureSkipVerify: true},
		),
	)
	if cfg.Insecure {
		restProxyTLSOpt = grpc.WithTransportCredentials(
			insecure.NewCredentials(),
		)
	}

	// Normalize the dial target for the REST gateway. If the listen
	// address uses 0.0.0.0 or an empty host, replace with localhost
	// so the loopback connection is routable on all platforms.
	dialAddr := normalizeDialAddr(cfg.ListenAddr)

	// Use RegisterAdminHandlerFromEndpoint (loopback dial) so that
	// REST requests go through the full gRPC interceptor chain,
	// including macaroon authentication.
	mux := gateway.NewServeMux(customMarshalerOption)
	err = adminrpc.RegisterAdminHandlerFromEndpoint(
		ctxc, mux, dialAddr, []grpc.DialOption{
			restProxyTLSOpt,
		},
	)
	if err != nil {
		cleanup()
		return nil, nil, nil, err
	}

	corsHandler := allowCORS(mux, cfg.Admin.CORSOrigins)
	priorityServices = append(priorityServices, proxy.NewLocalService(
		corsHandler, func(r *http.Request) bool {
			return strings.HasPrefix(
				r.URL.Path, adminRESTPrefix,
			)
		},
	))

	log.Infof("Admin gRPC/REST API enabled")

	// Wire the embedded dashboard if it was compiled in (build tag
	// !nodashboard). When nil, the dashboard is not served.
	dashFS, err := DashboardFS()
	if err != nil {
		cleanup()
		return nil, nil, nil, fmt.Errorf("unable to load embedded "+
			"dashboard: %w", err)
	}

	if dashFS != nil {
		// Generate a macaroon from the root key to attach to
		// server-side proxied requests to the admin REST API.
		mac, err := admin.GenerateAdminMacaroon(rootKey)
		if err != nil {
			cleanup()
			return nil, nil, nil, fmt.Errorf("unable to generate "+
				"dashboard macaroon: %w", err)
		}
		macBytes, err := mac.MarshalBinary()
		if err != nil {
			cleanup()
			return nil, nil, nil, fmt.Errorf("unable to marshal "+
				"dashboard macaroon: %w", err)
		}
		macHex := hex.EncodeToString(macBytes)

		// dashboardProxyPrefix is the path the dashboard JS uses to
		// reach the admin REST API. The Go server strips this prefix
		// and forwards internally to adminRESTPrefix.
		const dashboardProxyPrefix = "/api/proxy/"

		// requireLoopback rejects requests that do not originate
		// from a loopback address (127.0.0.1 / ::1). The
		// dashboard proxy injects admin credentials server-side,
		// so it must only be accessible locally.
		requireLoopback := func(next http.Handler) http.Handler {
			return http.HandlerFunc(
				func(w http.ResponseWriter, r *http.Request) {
					host, _, err := net.SplitHostPort(
						r.RemoteAddr,
					)
					if err != nil {
						http.Error(
							w, "forbidden",
							http.StatusForbidden,
						)
						return
					}
					ip := net.ParseIP(host)
					if ip == nil || !ip.IsLoopback() {
						http.Error(
							w, "forbidden",
							http.StatusForbidden,
						)
						return
					}
					next.ServeHTTP(w, r)
				},
			)
		}

		// addSecurityHeaders wraps a handler to set standard
		// browser security headers on every response.
		addSecurityHeaders := func(next http.Handler) http.Handler {
			return http.HandlerFunc(
				func(w http.ResponseWriter, r *http.Request) {
					w.Header().Set(
						"X-Frame-Options", "DENY",
					)
					w.Header().Set(
						"X-Content-Type-Options",
						"nosniff",
					)
					w.Header().Set(
						"Referrer-Policy",
						"strict-origin-when-cross-origin",
					)
					w.Header().Set(
						"Content-Security-Policy",
						"default-src 'self'; "+
							"style-src 'self' "+
							"'unsafe-inline'; "+
							"script-src 'self' "+
							"'unsafe-inline'",
					)
					next.ServeHTTP(w, r)
				},
			)
		}

		// csrfProtect rejects mutating requests (non-GET/HEAD)
		// that fail CSRF validation. Two checks are applied:
		//
		// 1. If an Origin or Referer header is present, it must
		//    match the request Host.
		// 2. The X-Requested-With header must be set (to any
		//    value). Simple cross-origin requests (form posts,
		//    img tags) cannot set custom headers, so this blocks
		//    CSRF even when Origin/Referer are absent.
		csrfProtect := func(next http.Handler) http.Handler {
			return http.HandlerFunc(
				func(w http.ResponseWriter, r *http.Request) {
					if r.Method != "GET" &&
						r.Method != "HEAD" {

						origin := r.Header.Get("Origin")
						if origin == "" {
							origin = r.Header.Get(
								"Referer",
							)
						}
						if origin != "" &&
							!isOriginAllowed(
								origin,
								r.Host,
							) {

							http.Error(
								w,
								"forbidden: "+
									"cross-origin "+
									"request",
								http.StatusForbidden,
							)
							return
						}

						// Require X-Requested-With
						// header on all mutating
						// requests. This cannot be
						// set by simple cross-origin
						// requests.
						if r.Header.Get(
							"X-Requested-With",
						) == "" {
							http.Error(
								w,
								"forbidden: "+
									"missing "+
									"X-Requested-With",
								http.StatusForbidden,
							)
							return
						}
					}
					next.ServeHTTP(w, r)
				},
			)
		}

		// safeQueryValue validates a query parameter value.
		// It enforces maximum length and rejects control
		// characters.
		safeQueryValue := func(v string, maxLen int) bool {
			if len(v) > maxLen {
				return false
			}
			for _, c := range v {
				if c < 0x20 || c == 0x7f {
					return false
				}
			}
			return true
		}

		// validateInt checks that a query value is a valid
		// non-negative integer within the given max.
		validateInt := func(v string, max int) bool {
			n, err := strconv.Atoi(v)
			return err == nil && n >= 0 && n <= max
		}

		// allowedQueryParams maps parameter names to their
		// validation functions. Parameters not in this map are
		// stripped. Parameters whose values fail validation are
		// also stripped.
		type queryValidator func(string) bool
		allowedQueryParams := map[string]queryValidator{
			"limit": func(v string) bool {
				return validateInt(v, 1000)
			},
			"offset": func(v string) bool {
				return validateInt(v, 1000000)
			},
			"from": func(v string) bool {
				return safeQueryValue(v, 30)
			},
			"to": func(v string) bool {
				return safeQueryValue(v, 30)
			},
			"service": func(v string) bool {
				return safeQueryValue(v, 128)
			},
			"state": func(v string) bool {
				return safeQueryValue(v, 128)
			},
			"name": func(v string) bool {
				return safeQueryValue(v, 128)
			},
		}

		safeSegment := regexp.MustCompile(`^[\w-]+$`)
		proxyHandler := http.HandlerFunc(
			func(w http.ResponseWriter, r *http.Request) {
				raw := strings.TrimPrefix(
					r.URL.Path, dashboardProxyPrefix,
				)

				// Filter empty segments so trailing slashes
				// do not cause a spurious 400.
				segments := strings.Split(raw, "/")
				filtered := segments[:0]
				for _, seg := range segments {
					if seg != "" {
						filtered = append(
							filtered, seg,
						)
					}
				}

				for _, seg := range filtered {
					if !safeSegment.MatchString(seg) {
						http.Error(
							w, "bad request",
							http.StatusBadRequest,
						)
						return
					}
				}

				r2 := r.Clone(r.Context())
				r2.URL.Path = adminRESTPrefix +
					strings.Join(filtered, "/")

				// Allowlist query parameters by name and
				// validate their values.
				orig := r2.URL.Query()
				clean := make(url.Values)
				for k, vals := range orig {
					validate, ok := allowedQueryParams[k]
					if !ok {
						continue
					}
					for _, v := range vals {
						if validate(v) {
							clean.Add(k, v)
						}
					}
				}
				r2.URL.RawQuery = clean.Encode()

				// Construct a fresh header set with only
				// the entries the admin API needs. This
				// avoids forwarding client-controlled
				// headers like X-Forwarded-For or
				// Authorization.
				r2.Header = make(http.Header)
				if ct := r.Header.Get("Content-Type"); ct != "" {
					r2.Header.Set("Content-Type", ct)
				}
				if accept := r.Header.Get("Accept"); accept != "" {
					r2.Header.Set("Accept", accept)
				}
				r2.Header.Set(
					"Grpc-Metadata-Macaroon", macHex,
				)
				mux.ServeHTTP(w, r2)
			},
		)

		// Wrap the proxy handler with security middleware:
		// loopback → CSRF → security headers → handler.
		wrappedProxy := requireLoopback(
			csrfProtect(addSecurityHeaders(proxyHandler)),
		)
		priorityServices = append(
			priorityServices, proxy.NewLocalService(
				wrappedProxy,
				func(r *http.Request) bool {
					return strings.HasPrefix(
						r.URL.Path,
						dashboardProxyPrefix,
					)
				},
			),
		)

		// Catch-all static file server with index.html fallback for
		// client-side routing (SPA deep-link support). This is added
		// to fallbackServices so it is only checked after proxy
		// backend matching — otherwise it would hijack all traffic
		// intended for configured backend services.
		dashHandler := http.HandlerFunc(
			func(w http.ResponseWriter, r *http.Request) {
				path := strings.TrimPrefix(r.URL.Path, "/")

				// Serve the file if it exists and is not a
				// directory (e.g. _next/ assets).
				if fi, statErr := fs.Stat(dashFS, path); statErr == nil && !fi.IsDir() {
					http.ServeFileFS(w, r, dashFS, path)
					return
				}

				// For directory paths, serve the index.html
				// nested inside (Next.js trailingSlash layout).
				indexPath := strings.TrimSuffix(path, "/") +
					"/index.html"
				if _, statErr := fs.Stat(dashFS, indexPath); statErr == nil {
					http.ServeFileFS(w, r, dashFS, indexPath)
					return
				}

				// Fall back to root index.html for unknown
				// paths (dynamic client-side routes).
				http.ServeFileFS(w, r, dashFS, "index.html")
			},
		)

		// Wrap the dashboard static handler with loopback and
		// security headers.
		wrappedDash := requireLoopback(
			addSecurityHeaders(dashHandler),
		)
		fallbackServices = append(
			fallbackServices, proxy.NewLocalService(
				wrappedDash,
				func(r *http.Request) bool {
					return true
				},
			),
		)

		log.Infof("Admin dashboard embedded and serving")
	}

	return priorityServices, fallbackServices, cleanup, nil
}

// initSQLStores creates all SQL-backed stores from a BaseDB instance. This
// is shared between the postgres and sqlite backends.
func initSQLStores(db *aperturedb.BaseDB) (
	*aperturedb.SecretsStore,
	*aperturedb.OnionStore,
	*aperturedb.LNCSessionsStore,
	*aperturedb.L402TransactionsStore,
	*aperturedb.ServicesStore) {

	dbSecretTxer := aperturedb.NewTransactionExecutor(db,
		func(tx *sql.Tx) aperturedb.SecretsDB {
			return db.WithTx(tx)
		},
	)
	secretStore := aperturedb.NewSecretsStore(dbSecretTxer)

	dbOnionTxer := aperturedb.NewTransactionExecutor(db,
		func(tx *sql.Tx) aperturedb.OnionDB {
			return db.WithTx(tx)
		},
	)
	onionStore := aperturedb.NewOnionStore(dbOnionTxer)

	dbLNCTxer := aperturedb.NewTransactionExecutor(db,
		func(tx *sql.Tx) aperturedb.LNCSessionsDB {
			return db.WithTx(tx)
		},
	)
	lncStore := aperturedb.NewLNCSessionsStore(dbLNCTxer)

	dbTxnTxer := aperturedb.NewTransactionExecutor(db,
		func(tx *sql.Tx) aperturedb.L402TransactionsDB {
			return db.WithTx(tx)
		},
	)
	txnStore := aperturedb.NewL402TransactionsStore(dbTxnTxer)

	dbSvcTxer := aperturedb.NewTransactionExecutor(db,
		func(tx *sql.Tx) aperturedb.ServicesDB {
			return db.WithTx(tx)
		},
	)
	svcStore := aperturedb.NewServicesStore(dbSvcTxer)

	return secretStore, onionStore, lncStore, txnStore, svcStore
}

// mergeServicesFromDB loads persisted services from the database and merges
// them with config file services. DB services override config services by name
// so that runtime changes survive restarts. Config services not in the DB are
// preserved as-is.
func mergeServicesFromDB(configServices []*proxy.Service,
	svcStore *aperturedb.ServicesStore) []*proxy.Service {

	if svcStore == nil {
		return configServices
	}

	ctx, cancel := context.WithTimeout(
		context.Background(), aperturedb.DefaultStoreTimeout,
	)
	defer cancel()

	dbRows, err := svcStore.ListServices(ctx)
	if err != nil {
		log.Warnf("Unable to load persisted services from DB, "+
			"using config only: %v", err)
		return configServices
	}

	if len(dbRows) == 0 {
		return configServices
	}

	// Build a map of DB services keyed by name.
	dbByName := make(map[string]*proxy.Service, len(dbRows))
	for _, row := range dbRows {
		dbByName[row.Name] = &proxy.Service{
			Name:       row.Name,
			Address:    row.Address,
			Protocol:   row.Protocol,
			HostRegexp: row.HostRegexp,
			PathRegexp: row.PathRegexp,
			Price:      row.Price,
			Auth:       auth.Level(row.Auth),
		}
	}

	// Start with DB services, then add config services that are not
	// already in the DB.
	merged := make([]*proxy.Service, 0, len(dbByName)+len(configServices))
	for _, svc := range dbByName {
		merged = append(merged, svc)
	}
	for _, svc := range configServices {
		if _, exists := dbByName[svc.Name]; !exists {
			merged = append(merged, svc)
		}
	}

	log.Infof("Loaded %d services from DB, %d from config (%d merged "+
		"total)", len(dbByName), len(configServices), len(merged))

	return merged
}

// normalizeDialAddr replaces a wildcard or empty host in an address with
// "localhost" so that gRPC dial targets are routable on all platforms.
func normalizeDialAddr(addr string) string {
	host, port, err := net.SplitHostPort(addr)
	if err != nil {
		return addr
	}
	if host == "" || host == "0.0.0.0" || host == "::" {
		return net.JoinHostPort("localhost", port)
	}
	return addr
}

// isOriginAllowed checks whether the given origin URL's host matches the
// request host. This is used for CSRF protection on the dashboard proxy.
func isOriginAllowed(origin, requestHost string) bool {
	parsed, err := url.Parse(origin)
	if err != nil {
		return false
	}

	originHost := parsed.Host
	if originHost == "" {
		originHost = parsed.Path
	}

	return originHost == requestHost
}

// asMintTransactionStore safely converts a concrete transaction store pointer
// into the mint.TransactionStore interface. If the concrete pointer is nil, a
// true nil interface is returned.
func asMintTransactionStore(
	txnStore *aperturedb.L402TransactionsStore) mint.TransactionStore {

	if txnStore == nil {
		return nil
	}

	return txnStore
}

// createProxy creates the proxy with all the services it needs.
// adminPriorityServices are checked before proxy backend matching (e.g. admin
// gRPC, REST, dashboard proxy). adminFallbackServices are checked after proxy
// backend matching fails (e.g. dashboard catch-all static file server).
func createProxy(cfg *Config, challenger challenger.Challenger,
	store mint.SecretStore, txnStore mint.TransactionStore,
	adminPriorityServices, adminFallbackServices []proxy.LocalService,
) (*proxy.Proxy, func(), error) {

	minter := mint.New(&mint.Config{
		Challenger:       challenger,
		Secrets:          store,
		ServiceLimiter:   newStaticServiceLimiter(cfg.Services),
		Now:              time.Now,
		TransactionStore: txnStore,
	})
	authenticator := auth.NewL402Authenticator(minter, challenger)

	// By default the static file server only returns 404 answers for
	// security reasons. Serving files from the staticRoot directory has to
	// be enabled intentionally.
	staticServer := http.NotFoundHandler()
	if cfg.ServeStatic {
		if len(strings.TrimSpace(cfg.StaticRoot)) == 0 {
			return nil, nil, fmt.Errorf("staticroot cannot be " +
				"empty, must contain path to directory that " +
				"contains index.html")
		}
		staticServer = http.FileServer(http.Dir(cfg.StaticRoot))
	}

	var (
		localServices []proxy.LocalService
		proxyCleanup  = func() {}
	)

	if cfg.HashMail.Enabled {
		hashMailServices, cleanup, err := createHashMailServer(cfg)
		if err != nil {
			return nil, nil, err
		}

		localServices = append(localServices, hashMailServices...)
		proxyCleanup = cleanup
	}

	// The static file server must be last since it will match all calls
	// that make it to it.
	localServices = append(localServices, proxy.NewLocalService(
		staticServer, func(r *http.Request) bool {
			return true
		},
	))

	// Append admin fallback services (e.g. dashboard catch-all) after
	// hashmail and the static file server so they are checked in the
	// correct order within localServices.
	localServices = append(localServices, adminFallbackServices...)

	prxy, err := proxy.New(
		authenticator, cfg.Services, cfg.Blocklist,
		adminPriorityServices, localServices...,
	)
	return prxy, proxyCleanup, err
}

// createHashMailServer creates the gRPC server for the hash mail message
// gateway and an additional REST and WebSocket capable proxy for that gRPC
// server.
func createHashMailServer(cfg *Config) ([]proxy.LocalService, func(), error) {
	var localServices []proxy.LocalService

	serverOpts := []grpc.ServerOption{
		grpc.KeepaliveEnforcementPolicy(keepalive.EnforcementPolicy{
			MinTime: time.Minute,
		}),
	}

	// Before we register both servers, we'll also ensure that the collector
	// will export latency metrics for the histogram.
	if cfg.Prometheus != nil && cfg.Prometheus.Enabled {
		grpc_prometheus.EnableHandlingTimeHistogram()
		serverOpts = append(
			serverOpts,
			grpc.ChainUnaryInterceptor(
				grpc_prometheus.UnaryServerInterceptor,
			),
			grpc.ChainStreamInterceptor(
				grpc_prometheus.StreamServerInterceptor,
			),
		)
	}

	// Create a gRPC server for the hashmail server.
	hashMailServer := newHashMailServer(hashMailServerConfig{
		msgRate:           cfg.HashMail.MessageRate,
		msgBurstAllowance: cfg.HashMail.MessageBurstAllowance,
		staleTimeout:      cfg.HashMail.StaleTimeout,
	})
	hashMailGRPC := grpc.NewServer(serverOpts...)
	hashmailrpc.RegisterHashMailServer(hashMailGRPC, hashMailServer)
	localServices = append(localServices, proxy.NewLocalService(
		hashMailGRPC, func(r *http.Request) bool {
			return strings.HasPrefix(r.URL.Path, hashMailGRPCPrefix)
		}),
	)

	// Export the gRPC information for the public gRPC server.
	if cfg.Prometheus != nil && cfg.Prometheus.Enabled {
		grpc_prometheus.Register(hashMailGRPC)
	}

	// And a REST proxy for it as well.
	// The default JSON marshaler of the REST proxy only sets OrigName to
	// true, which instructs it to use the same field names as specified in
	// the proto file and not switch to camel case. What we also want is
	// that the marshaler prints all values, even if they are falsey.
	customMarshalerOption := gateway.WithMarshalerOption(
		gateway.MIMEWildcard, &gateway.JSONPb{
			MarshalOptions: protojson.MarshalOptions{
				UseProtoNames:   true,
				EmitUnpopulated: true,
			},
		},
	)

	// We'll also create and start an accompanying proxy to serve clients
	// through REST.
	ctxc, cancel := context.WithCancel(context.Background())
	proxyCleanup := func() {
		hashMailServer.Stop()
		cancel()
	}

	// The REST proxy connects to our main listen address. If we're serving
	// TLS, we don't care about the certificate being valid, as we issue it
	// ourselves. If we are serving without TLS (for example when behind a
	// load balancer), we need to connect to ourselves without using TLS as
	// well.
	restProxyTLSOpt := grpc.WithTransportCredentials(credentials.NewTLS(
		&tls.Config{InsecureSkipVerify: true},
	))
	if cfg.Insecure {
		restProxyTLSOpt = grpc.WithTransportCredentials(
			insecure.NewCredentials(),
		)
	}

	mux := gateway.NewServeMux(customMarshalerOption)
	err := hashmailrpc.RegisterHashMailHandlerFromEndpoint(
		ctxc, mux, cfg.ListenAddr, []grpc.DialOption{
			restProxyTLSOpt,
		},
	)
	if err != nil {
		proxyCleanup()

		return nil, nil, err
	}

	// Wrap the default grpc-gateway handler with the WebSocket handler.
	// We enable WebSocket-level pings to keep the underlying connection
	// alive through intermediary proxies and load balancers that may
	// silently drop idle WebSocket connections.
	restHandler := lnrpc.NewWebSocketProxy(
		mux, log, cfg.WsPingInterval, cfg.WsPongWait,
		clientStreamingURIs,
	)

	// Create our proxy chain now. A request will pass
	// through the following chain:
	// req ---> CORS handler --> WS proxy ---> REST proxy --> gRPC endpoint
	corsHandler := allowCORS(restHandler, []string{"*"})
	localServices = append(localServices, proxy.NewLocalService(
		corsHandler, func(r *http.Request) bool {
			return strings.HasPrefix(r.URL.Path, hashMailRESTPrefix)
		},
	))

	return localServices, proxyCleanup, nil
}

// cleanup closes the given server and shuts down the log rotator.
func cleanup(server io.Closer, proxy io.Closer) {
	if err := proxy.Close(); err != nil {
		log.Errorf("Error terminating proxy: %v", err)
	}
	err := server.Close()
	if err != nil {
		log.Errorf("Error closing server: %v", err)
	}
	log.Info("Shutdown complete")
	err = logWriter.Close()
	if err != nil {
		log.Errorf("Could not close log rotator: %v", err)
	}
}

// allowCORS wraps the given http.Handler with a function that adds the
// Access-Control-Allow-Origin header to the response.
func allowCORS(handler http.Handler, origins []string) http.Handler {
	allowHeaders := "Access-Control-Allow-Headers"
	allowMethods := "Access-Control-Allow-Methods"
	allowOrigin := "Access-Control-Allow-Origin"

	// If the user didn't supply any origins that means CORS is disabled
	// and we should return the original handler.
	if len(origins) == 0 {
		return handler
	}

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		origin := r.Header.Get("Origin")

		// Skip everything if the browser doesn't send the Origin field.
		if origin == "" {
			handler.ServeHTTP(w, r)
			return
		}

		// Set the static header fields first.
		w.Header().Set(
			allowHeaders,
			"Content-Type, Accept, Grpc-Metadata-Macaroon",
		)
		w.Header().Set(allowMethods, "GET, POST, PUT, DELETE")

		// Either we allow all origins or the incoming request matches
		// a specific origin in our list of allowed origins.
		for _, allowedOrigin := range origins {
			if allowedOrigin == "*" || origin == allowedOrigin {
				// Only set allowed origin to requested origin.
				w.Header().Set(allowOrigin, origin)

				break
			}
		}

		// For a pre-flight request we only need to send the headers
		// back. No need to call the rest of the chain.
		if r.Method == "OPTIONS" {
			return
		}

		// Everything's prepared now, we can pass the request along the
		// chain of handlers.
		handler.ServeHTTP(w, r)
	})
}
