// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: admin.proto

package adminrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthScheme specifies which payment authentication scheme(s) a service uses.
// L402 is the default for backwards compatibility with existing deployments.
type AuthScheme int32

const (
	// AUTH_SCHEME_L402 is the default L402 (macaroon + preimage) scheme.
	AuthScheme_AUTH_SCHEME_L402 AuthScheme = 0
	// AUTH_SCHEME_MPP is the Payment HTTP Authentication Scheme (charge
	// intent only, no sessions).
	AuthScheme_AUTH_SCHEME_MPP AuthScheme = 1
	// AUTH_SCHEME_L402_MPP enables both L402 and MPP simultaneously. The
	// proxy issues challenges for both schemes and accepts either.
	AuthScheme_AUTH_SCHEME_L402_MPP AuthScheme = 2
)

// Enum value maps for AuthScheme.
var (
	AuthScheme_name = map[int32]string{
		0: "AUTH_SCHEME_L402",
		1: "AUTH_SCHEME_MPP",
		2: "AUTH_SCHEME_L402_MPP",
	}
	AuthScheme_value = map[string]int32{
		"AUTH_SCHEME_L402":     0,
		"AUTH_SCHEME_MPP":      1,
		"AUTH_SCHEME_L402_MPP": 2,
	}
)

func (x AuthScheme) Enum() *AuthScheme {
	p := new(AuthScheme)
	*p = x
	return p
}

func (x AuthScheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthScheme) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_proto_enumTypes[0].Descriptor()
}

func (AuthScheme) Type() protoreflect.EnumType {
	return &file_admin_proto_enumTypes[0]
}

func (x AuthScheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthScheme.Descriptor instead.
func (AuthScheme) EnumDescriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Network    string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	ListenAddr string                 `protobuf:"bytes,2,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	Insecure   bool                   `protobuf:"varint,3,opt,name=insecure,proto3" json:"insecure,omitempty"`
	// mpp_enabled indicates whether the MPP (Payment HTTP Auth Scheme) is
	// enabled globally.
	MppEnabled bool `protobuf:"varint,4,opt,name=mpp_enabled,json=mppEnabled,proto3" json:"mpp_enabled,omitempty"`
	// sessions_enabled indicates whether MPP session intents are enabled.
	SessionsEnabled bool `protobuf:"varint,5,opt,name=sessions_enabled,json=sessionsEnabled,proto3" json:"sessions_enabled,omitempty"`
	// mpp_realm is the realm string used in MPP challenge headers.
	MppRealm      string `protobuf:"bytes,6,opt,name=mpp_realm,json=mppRealm,proto3" json:"mpp_realm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *GetInfoResponse) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *GetInfoResponse) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *GetInfoResponse) GetMppEnabled() bool {
	if x != nil {
		return x.MppEnabled
	}
	return false
}

func (x *GetInfoResponse) GetSessionsEnabled() bool {
	if x != nil {
		return x.SessionsEnabled
	}
	return false
}

func (x *GetInfoResponse) GetMppRealm() string {
	if x != nil {
		return x.MppRealm
	}
	return ""
}

type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

type GetHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResponse.ProtoReflect.Descriptor instead.
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListServicesResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type Service struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address    string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Protocol   string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	HostRegexp string                 `protobuf:"bytes,4,opt,name=host_regexp,json=hostRegexp,proto3" json:"host_regexp,omitempty"`
	PathRegexp string                 `protobuf:"bytes,5,opt,name=path_regexp,json=pathRegexp,proto3" json:"path_regexp,omitempty"`
	Price      int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Auth       string                 `protobuf:"bytes,7,opt,name=auth,proto3" json:"auth,omitempty"`
	// auth_scheme specifies which payment auth scheme(s) are used for this
	// service. Defaults to AUTH_SCHEME_L402 for backwards compatibility.
	AuthScheme    AuthScheme `protobuf:"varint,8,opt,name=auth_scheme,json=authScheme,proto3,enum=adminrpc.AuthScheme" json:"auth_scheme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{6}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Service) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Service) GetHostRegexp() string {
	if x != nil {
		return x.HostRegexp
	}
	return ""
}

func (x *Service) GetPathRegexp() string {
	if x != nil {
		return x.PathRegexp
	}
	return ""
}

func (x *Service) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Service) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *Service) GetAuthScheme() AuthScheme {
	if x != nil {
		return x.AuthScheme
	}
	return AuthScheme_AUTH_SCHEME_L402
}

type CreateServiceRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address    string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Protocol   string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	HostRegexp string                 `protobuf:"bytes,4,opt,name=host_regexp,json=hostRegexp,proto3" json:"host_regexp,omitempty"`
	PathRegexp string                 `protobuf:"bytes,5,opt,name=path_regexp,json=pathRegexp,proto3" json:"path_regexp,omitempty"`
	Price      int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Auth       string                 `protobuf:"bytes,7,opt,name=auth,proto3" json:"auth,omitempty"`
	// auth_scheme specifies which payment auth scheme(s) to use. Defaults to
	// AUTH_SCHEME_L402 if unset.
	AuthScheme    AuthScheme `protobuf:"varint,8,opt,name=auth_scheme,json=authScheme,proto3,enum=adminrpc.AuthScheme" json:"auth_scheme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceRequest) Reset() {
	*x = CreateServiceRequest{}
	mi := &file_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequest) ProtoMessage() {}

func (x *CreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{7}
}

func (x *CreateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServiceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateServiceRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *CreateServiceRequest) GetHostRegexp() string {
	if x != nil {
		return x.HostRegexp
	}
	return ""
}

func (x *CreateServiceRequest) GetPathRegexp() string {
	if x != nil {
		return x.PathRegexp
	}
	return ""
}

func (x *CreateServiceRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateServiceRequest) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *CreateServiceRequest) GetAuthScheme() AuthScheme {
	if x != nil {
		return x.AuthScheme
	}
	return AuthScheme_AUTH_SCHEME_L402
}

type UpdateServiceRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address    string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Protocol   string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	HostRegexp string                 `protobuf:"bytes,4,opt,name=host_regexp,json=hostRegexp,proto3" json:"host_regexp,omitempty"`
	PathRegexp string                 `protobuf:"bytes,5,opt,name=path_regexp,json=pathRegexp,proto3" json:"path_regexp,omitempty"`
	Price      *int64                 `protobuf:"varint,6,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Auth       string                 `protobuf:"bytes,7,opt,name=auth,proto3" json:"auth,omitempty"`
	// auth_scheme specifies which payment auth scheme(s) to use.
	AuthScheme    AuthScheme `protobuf:"varint,8,opt,name=auth_scheme,json=authScheme,proto3,enum=adminrpc.AuthScheme" json:"auth_scheme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceRequest) Reset() {
	*x = UpdateServiceRequest{}
	mi := &file_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequest) ProtoMessage() {}

func (x *UpdateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateServiceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateServiceRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *UpdateServiceRequest) GetHostRegexp() string {
	if x != nil {
		return x.HostRegexp
	}
	return ""
}

func (x *UpdateServiceRequest) GetPathRegexp() string {
	if x != nil {
		return x.PathRegexp
	}
	return ""
}

func (x *UpdateServiceRequest) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateServiceRequest) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *UpdateServiceRequest) GetAuthScheme() AuthScheme {
	if x != nil {
		return x.AuthScheme
	}
	return AuthScheme_AUTH_SCHEME_L402
}

type DeleteServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceRequest) Reset() {
	*x = DeleteServiceRequest{}
	mi := &file_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceRequest) ProtoMessage() {}

func (x *DeleteServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceResponse) Reset() {
	*x = DeleteServiceResponse{}
	mi := &file_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceResponse) ProtoMessage() {}

func (x *DeleteServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceResponse.ProtoReflect.Descriptor instead.
func (*DeleteServiceResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteServiceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ListTransactionsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ListTransactionsRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ListTransactionsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ListTransactionsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ListTransactionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTransactionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{12}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTransactionsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TokenId       string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	PaymentHash   string                 `protobuf:"bytes,3,opt,name=payment_hash,json=paymentHash,proto3" json:"payment_hash,omitempty"`
	ServiceName   string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	PriceSats     int64                  `protobuf:"varint,5,opt,name=price_sats,json=priceSats,proto3" json:"price_sats,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SettledAt     string                 `protobuf:"bytes,8,opt,name=settled_at,json=settledAt,proto3" json:"settled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{13}
}

func (x *Transaction) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *Transaction) GetPaymentHash() string {
	if x != nil {
		return x.PaymentHash
	}
	return ""
}

func (x *Transaction) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Transaction) GetPriceSats() int64 {
	if x != nil {
		return x.PriceSats
	}
	return 0
}

func (x *Transaction) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Transaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Transaction) GetSettledAt() string {
	if x != nil {
		return x.SettledAt
	}
	return ""
}

type ListTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensRequest) Reset() {
	*x = ListTokensRequest{}
	mi := &file_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensRequest) ProtoMessage() {}

func (x *ListTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensRequest.ProtoReflect.Descriptor instead.
func (*ListTokensRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{14}
}

func (x *ListTokensRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTokensRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*Transaction         `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensResponse) Reset() {
	*x = ListTokensResponse{}
	mi := &file_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensResponse) ProtoMessage() {}

func (x *ListTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensResponse.ProtoReflect.Descriptor instead.
func (*ListTokensResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{15}
}

func (x *ListTokensResponse) GetTokens() []*Transaction {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *ListTokensResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{16}
}

func (x *RevokeTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{17}
}

func (x *RevokeTokenResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{18}
}

func (x *GetStatsRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetStatsRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type GetStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalRevenueSats int64                  `protobuf:"varint,1,opt,name=total_revenue_sats,json=totalRevenueSats,proto3" json:"total_revenue_sats,omitempty"`
	TransactionCount int64                  `protobuf:"varint,2,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	ServiceBreakdown []*ServiceRevenue      `protobuf:"bytes,3,rep,name=service_breakdown,json=serviceBreakdown,proto3" json:"service_breakdown,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{19}
}

func (x *GetStatsResponse) GetTotalRevenueSats() int64 {
	if x != nil {
		return x.TotalRevenueSats
	}
	return 0
}

func (x *GetStatsResponse) GetTransactionCount() int64 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

func (x *GetStatsResponse) GetServiceBreakdown() []*ServiceRevenue {
	if x != nil {
		return x.ServiceBreakdown
	}
	return nil
}

type ServiceRevenue struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceName      string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	TotalRevenueSats int64                  `protobuf:"varint,2,opt,name=total_revenue_sats,json=totalRevenueSats,proto3" json:"total_revenue_sats,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServiceRevenue) Reset() {
	*x = ServiceRevenue{}
	mi := &file_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRevenue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRevenue) ProtoMessage() {}

func (x *ServiceRevenue) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRevenue.ProtoReflect.Descriptor instead.
func (*ServiceRevenue) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{20}
}

func (x *ServiceRevenue) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceRevenue) GetTotalRevenueSats() int64 {
	if x != nil {
		return x.TotalRevenueSats
	}
	return 0
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\badminrpc\"\x10\n" +
	"\x0eGetInfoRequest\"\xd1\x01\n" +
	"\x0fGetInfoResponse\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x1f\n" +
	"\vlisten_addr\x18\x02 \x01(\tR\n" +
	"listenAddr\x12\x1a\n" +
	"\binsecure\x18\x03 \x01(\bR\binsecure\x12\x1f\n" +
	"\vmpp_enabled\x18\x04 \x01(\bR\n" +
	"mppEnabled\x12)\n" +
	"\x10sessions_enabled\x18\x05 \x01(\bR\x0fsessionsEnabled\x12\x1b\n" +
	"\tmpp_realm\x18\x06 \x01(\tR\bmppRealm\"\x12\n" +
	"\x10GetHealthRequest\"+\n" +
	"\x11GetHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x15\n" +
	"\x13ListServicesRequest\"E\n" +
	"\x14ListServicesResponse\x12-\n" +
	"\bservices\x18\x01 \x03(\v2\x11.adminrpc.ServiceR\bservices\"\xf6\x01\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x1f\n" +
	"\vhost_regexp\x18\x04 \x01(\tR\n" +
	"hostRegexp\x12\x1f\n" +
	"\vpath_regexp\x18\x05 \x01(\tR\n" +
	"pathRegexp\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12\x12\n" +
	"\x04auth\x18\a \x01(\tR\x04auth\x125\n" +
	"\vauth_scheme\x18\b \x01(\x0e2\x14.adminrpc.AuthSchemeR\n" +
	"authScheme\"\x83\x02\n" +
	"\x14CreateServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x1f\n" +
	"\vhost_regexp\x18\x04 \x01(\tR\n" +
	"hostRegexp\x12\x1f\n" +
	"\vpath_regexp\x18\x05 \x01(\tR\n" +
	"pathRegexp\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12\x12\n" +
	"\x04auth\x18\a \x01(\tR\x04auth\x125\n" +
	"\vauth_scheme\x18\b \x01(\x0e2\x14.adminrpc.AuthSchemeR\n" +
	"authScheme\"\x92\x02\n" +
	"\x14UpdateServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x1f\n" +
	"\vhost_regexp\x18\x04 \x01(\tR\n" +
	"hostRegexp\x12\x1f\n" +
	"\vpath_regexp\x18\x05 \x01(\tR\n" +
	"pathRegexp\x12\x19\n" +
	"\x05price\x18\x06 \x01(\x03H\x00R\x05price\x88\x01\x01\x12\x12\n" +
	"\x04auth\x18\a \x01(\tR\x04auth\x125\n" +
	"\vauth_scheme\x18\b \x01(\x0e2\x14.adminrpc.AuthSchemeR\n" +
	"authSchemeB\b\n" +
	"\x06_price\"*\n" +
	"\x14DeleteServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x15DeleteServiceResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xb1\x01\n" +
	"\x17ListTransactionsRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"v\n" +
	"\x18ListTransactionsResponse\x129\n" +
	"\ftransactions\x18\x01 \x03(\v2\x15.adminrpc.TransactionR\ftransactions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\xf1\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\x12!\n" +
	"\fpayment_hash\x18\x03 \x01(\tR\vpaymentHash\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"price_sats\x18\x05 \x01(\x03R\tpriceSats\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"settled_at\x18\b \x01(\tR\tsettledAt\"A\n" +
	"\x11ListTokensRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"d\n" +
	"\x12ListTokensResponse\x12-\n" +
	"\x06tokens\x18\x01 \x03(\v2\x15.adminrpc.TransactionR\x06tokens\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"/\n" +
	"\x12RevokeTokenRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\"-\n" +
	"\x13RevokeTokenResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"5\n" +
	"\x0fGetStatsRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"\xb4\x01\n" +
	"\x10GetStatsResponse\x12,\n" +
	"\x12total_revenue_sats\x18\x01 \x01(\x03R\x10totalRevenueSats\x12+\n" +
	"\x11transaction_count\x18\x02 \x01(\x03R\x10transactionCount\x12E\n" +
	"\x11service_breakdown\x18\x03 \x03(\v2\x18.adminrpc.ServiceRevenueR\x10serviceBreakdown\"a\n" +
	"\x0eServiceRevenue\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12,\n" +
	"\x12total_revenue_sats\x18\x02 \x01(\x03R\x10totalRevenueSats*Q\n" +
	"\n" +
	"AuthScheme\x12\x14\n" +
	"\x10AUTH_SCHEME_L402\x10\x00\x12\x13\n" +
	"\x0fAUTH_SCHEME_MPP\x10\x01\x12\x18\n" +
	"\x14AUTH_SCHEME_L402_MPP\x10\x022\xe9\x05\n" +
	"\x05Admin\x12>\n" +
	"\aGetInfo\x12\x18.adminrpc.GetInfoRequest\x1a\x19.adminrpc.GetInfoResponse\x12D\n" +
	"\tGetHealth\x12\x1a.adminrpc.GetHealthRequest\x1a\x1b.adminrpc.GetHealthResponse\x12M\n" +
	"\fListServices\x12\x1d.adminrpc.ListServicesRequest\x1a\x1e.adminrpc.ListServicesResponse\x12B\n" +
	"\rCreateService\x12\x1e.adminrpc.CreateServiceRequest\x1a\x11.adminrpc.Service\x12B\n" +
	"\rUpdateService\x12\x1e.adminrpc.UpdateServiceRequest\x1a\x11.adminrpc.Service\x12P\n" +
	"\rDeleteService\x12\x1e.adminrpc.DeleteServiceRequest\x1a\x1f.adminrpc.DeleteServiceResponse\x12Y\n" +
	"\x10ListTransactions\x12!.adminrpc.ListTransactionsRequest\x1a\".adminrpc.ListTransactionsResponse\x12G\n" +
	"\n" +
	"ListTokens\x12\x1b.adminrpc.ListTokensRequest\x1a\x1c.adminrpc.ListTokensResponse\x12J\n" +
	"\vRevokeToken\x12\x1c.adminrpc.RevokeTokenRequest\x1a\x1d.adminrpc.RevokeTokenResponse\x12A\n" +
	"\bGetStats\x12\x19.adminrpc.GetStatsRequest\x1a\x1a.adminrpc.GetStatsResponseB,Z*github.com/lightninglabs/aperture/adminrpcb\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_admin_proto_goTypes = []any{
	(AuthScheme)(0),                  // 0: adminrpc.AuthScheme
	(*GetInfoRequest)(nil),           // 1: adminrpc.GetInfoRequest
	(*GetInfoResponse)(nil),          // 2: adminrpc.GetInfoResponse
	(*GetHealthRequest)(nil),         // 3: adminrpc.GetHealthRequest
	(*GetHealthResponse)(nil),        // 4: adminrpc.GetHealthResponse
	(*ListServicesRequest)(nil),      // 5: adminrpc.ListServicesRequest
	(*ListServicesResponse)(nil),     // 6: adminrpc.ListServicesResponse
	(*Service)(nil),                  // 7: adminrpc.Service
	(*CreateServiceRequest)(nil),     // 8: adminrpc.CreateServiceRequest
	(*UpdateServiceRequest)(nil),     // 9: adminrpc.UpdateServiceRequest
	(*DeleteServiceRequest)(nil),     // 10: adminrpc.DeleteServiceRequest
	(*DeleteServiceResponse)(nil),    // 11: adminrpc.DeleteServiceResponse
	(*ListTransactionsRequest)(nil),  // 12: adminrpc.ListTransactionsRequest
	(*ListTransactionsResponse)(nil), // 13: adminrpc.ListTransactionsResponse
	(*Transaction)(nil),              // 14: adminrpc.Transaction
	(*ListTokensRequest)(nil),        // 15: adminrpc.ListTokensRequest
	(*ListTokensResponse)(nil),       // 16: adminrpc.ListTokensResponse
	(*RevokeTokenRequest)(nil),       // 17: adminrpc.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),      // 18: adminrpc.RevokeTokenResponse
	(*GetStatsRequest)(nil),          // 19: adminrpc.GetStatsRequest
	(*GetStatsResponse)(nil),         // 20: adminrpc.GetStatsResponse
	(*ServiceRevenue)(nil),           // 21: adminrpc.ServiceRevenue
}
var file_admin_proto_depIdxs = []int32{
	7,  // 0: adminrpc.ListServicesResponse.services:type_name -> adminrpc.Service
	0,  // 1: adminrpc.Service.auth_scheme:type_name -> adminrpc.AuthScheme
	0,  // 2: adminrpc.CreateServiceRequest.auth_scheme:type_name -> adminrpc.AuthScheme
	0,  // 3: adminrpc.UpdateServiceRequest.auth_scheme:type_name -> adminrpc.AuthScheme
	14, // 4: adminrpc.ListTransactionsResponse.transactions:type_name -> adminrpc.Transaction
	14, // 5: adminrpc.ListTokensResponse.tokens:type_name -> adminrpc.Transaction
	21, // 6: adminrpc.GetStatsResponse.service_breakdown:type_name -> adminrpc.ServiceRevenue
	1,  // 7: adminrpc.Admin.GetInfo:input_type -> adminrpc.GetInfoRequest
	3,  // 8: adminrpc.Admin.GetHealth:input_type -> adminrpc.GetHealthRequest
	5,  // 9: adminrpc.Admin.ListServices:input_type -> adminrpc.ListServicesRequest
	8,  // 10: adminrpc.Admin.CreateService:input_type -> adminrpc.CreateServiceRequest
	9,  // 11: adminrpc.Admin.UpdateService:input_type -> adminrpc.UpdateServiceRequest
	10, // 12: adminrpc.Admin.DeleteService:input_type -> adminrpc.DeleteServiceRequest
	12, // 13: adminrpc.Admin.ListTransactions:input_type -> adminrpc.ListTransactionsRequest
	15, // 14: adminrpc.Admin.ListTokens:input_type -> adminrpc.ListTokensRequest
	17, // 15: adminrpc.Admin.RevokeToken:input_type -> adminrpc.RevokeTokenRequest
	19, // 16: adminrpc.Admin.GetStats:input_type -> adminrpc.GetStatsRequest
	2,  // 17: adminrpc.Admin.GetInfo:output_type -> adminrpc.GetInfoResponse
	4,  // 18: adminrpc.Admin.GetHealth:output_type -> adminrpc.GetHealthResponse
	6,  // 19: adminrpc.Admin.ListServices:output_type -> adminrpc.ListServicesResponse
	7,  // 20: adminrpc.Admin.CreateService:output_type -> adminrpc.Service
	7,  // 21: adminrpc.Admin.UpdateService:output_type -> adminrpc.Service
	11, // 22: adminrpc.Admin.DeleteService:output_type -> adminrpc.DeleteServiceResponse
	13, // 23: adminrpc.Admin.ListTransactions:output_type -> adminrpc.ListTransactionsResponse
	16, // 24: adminrpc.Admin.ListTokens:output_type -> adminrpc.ListTokensResponse
	18, // 25: adminrpc.Admin.RevokeToken:output_type -> adminrpc.RevokeTokenResponse
	20, // 26: adminrpc.Admin.GetStats:output_type -> adminrpc.GetStatsResponse
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	file_admin_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		EnumInfos:         file_admin_proto_enumTypes,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
