// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: l402_transactions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countL402Transactions = `-- name: CountL402Transactions :one
SELECT count(*)
FROM l402_transactions
WHERE state = 'settled'
`

func (q *Queries) CountL402Transactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countL402Transactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countL402TransactionsByDateRange = `-- name: CountL402TransactionsByDateRange :one
SELECT count(*)
FROM l402_transactions
WHERE state = 'settled' AND settled_at >= $1 AND settled_at <= $2
`

type CountL402TransactionsByDateRangeParams struct {
	SettledAt   sql.NullTime
	SettledAt_2 sql.NullTime
}

func (q *Queries) CountL402TransactionsByDateRange(ctx context.Context, arg CountL402TransactionsByDateRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countL402TransactionsByDateRange, arg.SettledAt, arg.SettledAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countL402TransactionsByService = `-- name: CountL402TransactionsByService :one
SELECT count(*)
FROM l402_transactions
WHERE service_name = $1
`

func (q *Queries) CountL402TransactionsByService(ctx context.Context, serviceName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countL402TransactionsByService, serviceName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteL402TransactionByTokenID = `-- name: DeleteL402TransactionByTokenID :execrows
DELETE FROM l402_transactions
WHERE token_id = $1
`

func (q *Queries) DeleteL402TransactionByTokenID(ctx context.Context, tokenID []byte) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteL402TransactionByTokenID, tokenID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getL402RevenueByService = `-- name: GetL402RevenueByService :many
SELECT service_name, CAST(COALESCE(SUM(price_sats), 0) AS BIGINT) AS total_revenue
FROM l402_transactions
WHERE state = 'settled'
GROUP BY service_name
`

type GetL402RevenueByServiceRow struct {
	ServiceName  string
	TotalRevenue int64
}

func (q *Queries) GetL402RevenueByService(ctx context.Context) ([]GetL402RevenueByServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, getL402RevenueByService)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetL402RevenueByServiceRow
	for rows.Next() {
		var i GetL402RevenueByServiceRow
		if err := rows.Scan(&i.ServiceName, &i.TotalRevenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getL402RevenueByServiceAndDateRange = `-- name: GetL402RevenueByServiceAndDateRange :many
SELECT service_name, CAST(COALESCE(SUM(price_sats), 0) AS BIGINT) AS total_revenue
FROM l402_transactions
WHERE state = 'settled' AND settled_at >= $1 AND settled_at <= $2
GROUP BY service_name
`

type GetL402RevenueByServiceAndDateRangeParams struct {
	SettledAt   sql.NullTime
	SettledAt_2 sql.NullTime
}

type GetL402RevenueByServiceAndDateRangeRow struct {
	ServiceName  string
	TotalRevenue int64
}

func (q *Queries) GetL402RevenueByServiceAndDateRange(ctx context.Context, arg GetL402RevenueByServiceAndDateRangeParams) ([]GetL402RevenueByServiceAndDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getL402RevenueByServiceAndDateRange, arg.SettledAt, arg.SettledAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetL402RevenueByServiceAndDateRangeRow
	for rows.Next() {
		var i GetL402RevenueByServiceAndDateRangeRow
		if err := rows.Scan(&i.ServiceName, &i.TotalRevenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getL402SettledTransactionByTokenID = `-- name: GetL402SettledTransactionByTokenID :one
SELECT id, token_id, payment_hash, service_name, price_sats, state, created_at, settled_at, identifier_hash
FROM l402_transactions
WHERE token_id = $1 AND state = 'settled'
`

func (q *Queries) GetL402SettledTransactionByTokenID(ctx context.Context, tokenID []byte) (L402Transaction, error) {
	row := q.db.QueryRowContext(ctx, getL402SettledTransactionByTokenID, tokenID)
	var i L402Transaction
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.PaymentHash,
		&i.ServiceName,
		&i.PriceSats,
		&i.State,
		&i.CreatedAt,
		&i.SettledAt,
		&i.IdentifierHash,
	)
	return i, err
}

const getL402TotalRevenue = `-- name: GetL402TotalRevenue :one
SELECT CAST(COALESCE(SUM(price_sats), 0) AS BIGINT) AS total_revenue
FROM l402_transactions
WHERE state = 'settled'
`

func (q *Queries) GetL402TotalRevenue(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getL402TotalRevenue)
	var total_revenue int64
	err := row.Scan(&total_revenue)
	return total_revenue, err
}

const getL402TotalRevenueByDateRange = `-- name: GetL402TotalRevenueByDateRange :one
SELECT CAST(COALESCE(SUM(price_sats), 0) AS BIGINT) AS total_revenue
FROM l402_transactions
WHERE state = 'settled' AND settled_at >= $1 AND settled_at <= $2
`

type GetL402TotalRevenueByDateRangeParams struct {
	SettledAt   sql.NullTime
	SettledAt_2 sql.NullTime
}

func (q *Queries) GetL402TotalRevenueByDateRange(ctx context.Context, arg GetL402TotalRevenueByDateRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getL402TotalRevenueByDateRange, arg.SettledAt, arg.SettledAt_2)
	var total_revenue int64
	err := row.Scan(&total_revenue)
	return total_revenue, err
}

const getL402TransactionByIdentifierHash = `-- name: GetL402TransactionByIdentifierHash :one
SELECT id, token_id, payment_hash, service_name, price_sats, state, created_at, settled_at, identifier_hash
FROM l402_transactions
WHERE identifier_hash = $1
`

func (q *Queries) GetL402TransactionByIdentifierHash(ctx context.Context, identifierHash []byte) (L402Transaction, error) {
	row := q.db.QueryRowContext(ctx, getL402TransactionByIdentifierHash, identifierHash)
	var i L402Transaction
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.PaymentHash,
		&i.ServiceName,
		&i.PriceSats,
		&i.State,
		&i.CreatedAt,
		&i.SettledAt,
		&i.IdentifierHash,
	)
	return i, err
}

const getL402TransactionsByPaymentHash = `-- name: GetL402TransactionsByPaymentHash :many
SELECT id, token_id, payment_hash, service_name, price_sats, state, created_at, settled_at, identifier_hash
FROM l402_transactions
WHERE payment_hash = $1
`

func (q *Queries) GetL402TransactionsByPaymentHash(ctx context.Context, paymentHash []byte) ([]L402Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getL402TransactionsByPaymentHash, paymentHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []L402Transaction
	for rows.Next() {
		var i L402Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.PaymentHash,
			&i.ServiceName,
			&i.PriceSats,
			&i.State,
			&i.CreatedAt,
			&i.SettledAt,
			&i.IdentifierHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertL402Transaction = `-- name: InsertL402Transaction :one
INSERT INTO l402_transactions (
    token_id, payment_hash, service_name, price_sats, state, created_at,
    identifier_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id
`

type InsertL402TransactionParams struct {
	TokenID        []byte
	PaymentHash    []byte
	ServiceName    string
	PriceSats      int64
	State          string
	CreatedAt      time.Time
	IdentifierHash []byte
}

func (q *Queries) InsertL402Transaction(ctx context.Context, arg InsertL402TransactionParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertL402Transaction,
		arg.TokenID,
		arg.PaymentHash,
		arg.ServiceName,
		arg.PriceSats,
		arg.State,
		arg.CreatedAt,
		arg.IdentifierHash,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listL402Transactions = `-- name: ListL402Transactions :many
SELECT id, token_id, payment_hash, service_name, price_sats, state, created_at, settled_at, identifier_hash
FROM l402_transactions
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListL402TransactionsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListL402Transactions(ctx context.Context, arg ListL402TransactionsParams) ([]L402Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listL402Transactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []L402Transaction
	for rows.Next() {
		var i L402Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.PaymentHash,
			&i.ServiceName,
			&i.PriceSats,
			&i.State,
			&i.CreatedAt,
			&i.SettledAt,
			&i.IdentifierHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listL402TransactionsByDateRange = `-- name: ListL402TransactionsByDateRange :many
SELECT id, token_id, payment_hash, service_name, price_sats, state, created_at, settled_at, identifier_hash
FROM l402_transactions
WHERE created_at >= $1 AND created_at <= $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListL402TransactionsByDateRangeParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
	Limit       int32
	Offset      int32
}

func (q *Queries) ListL402TransactionsByDateRange(ctx context.Context, arg ListL402TransactionsByDateRangeParams) ([]L402Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listL402TransactionsByDateRange,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []L402Transaction
	for rows.Next() {
		var i L402Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.PaymentHash,
			&i.ServiceName,
			&i.PriceSats,
			&i.State,
			&i.CreatedAt,
			&i.SettledAt,
			&i.IdentifierHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listL402TransactionsByService = `-- name: ListL402TransactionsByService :many
SELECT id, token_id, payment_hash, service_name, price_sats, state, created_at, settled_at, identifier_hash
FROM l402_transactions
WHERE service_name = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListL402TransactionsByServiceParams struct {
	ServiceName string
	Limit       int32
	Offset      int32
}

func (q *Queries) ListL402TransactionsByService(ctx context.Context, arg ListL402TransactionsByServiceParams) ([]L402Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listL402TransactionsByService, arg.ServiceName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []L402Transaction
	for rows.Next() {
		var i L402Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.PaymentHash,
			&i.ServiceName,
			&i.PriceSats,
			&i.State,
			&i.CreatedAt,
			&i.SettledAt,
			&i.IdentifierHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listL402TransactionsByState = `-- name: ListL402TransactionsByState :many
SELECT id, token_id, payment_hash, service_name, price_sats, state, created_at, settled_at, identifier_hash
FROM l402_transactions
WHERE state = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListL402TransactionsByStateParams struct {
	State  string
	Limit  int32
	Offset int32
}

func (q *Queries) ListL402TransactionsByState(ctx context.Context, arg ListL402TransactionsByStateParams) ([]L402Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listL402TransactionsByState, arg.State, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []L402Transaction
	for rows.Next() {
		var i L402Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.PaymentHash,
			&i.ServiceName,
			&i.PriceSats,
			&i.State,
			&i.CreatedAt,
			&i.SettledAt,
			&i.IdentifierHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateL402TransactionState = `-- name: UpdateL402TransactionState :exec
UPDATE l402_transactions
SET state = $1, settled_at = $2
WHERE payment_hash = $3 AND state = 'pending'
`

type UpdateL402TransactionStateParams struct {
	State       string
	SettledAt   sql.NullTime
	PaymentHash []byte
}

func (q *Queries) UpdateL402TransactionState(ctx context.Context, arg UpdateL402TransactionStateParams) error {
	_, err := q.db.ExecContext(ctx, updateL402TransactionState, arg.State, arg.SettledAt, arg.PaymentHash)
	return err
}
