// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"
)

type L402Transaction struct {
	ID             int32
	TokenID        []byte
	PaymentHash    []byte
	ServiceName    string
	PriceSats      int64
	State          string
	CreatedAt      time.Time
	SettledAt      sql.NullTime
	IdentifierHash []byte
}

type LncSession struct {
	ID                 int32
	PassphraseWords    string
	PassphraseEntropy  []byte
	RemoteStaticPubKey []byte
	LocalStaticPrivKey []byte
	MailboxAddr        string
	CreatedAt          time.Time
	Expiry             sql.NullTime
	DevServer          bool
}

type Onion struct {
	PrivateKey []byte
	CreatedAt  time.Time
}

type Secret struct {
	ID        int32
	Hash      []byte
	Secret    []byte
	CreatedAt time.Time
}
