// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"
)

type L402Transaction struct {
	ID             int32
	TokenID        []byte
	PaymentHash    []byte
	IdentifierHash []byte
	ServiceName    string
	PriceSats      int64
	State          string
	AuthType       string
	CreatedAt      time.Time
	SettledAt      sql.NullTime
}

type LncSession struct {
	ID                 int32
	PassphraseWords    string
	PassphraseEntropy  []byte
	RemoteStaticPubKey []byte
	LocalStaticPrivKey []byte
	MailboxAddr        string
	CreatedAt          time.Time
	Expiry             sql.NullTime
	DevServer          bool
}

type MppSession struct {
	ID            int32
	SessionID     string
	PaymentHash   []byte
	DepositSats   int64
	SpentSats     int64
	ReturnInvoice string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Onion struct {
	PrivateKey []byte
	CreatedAt  time.Time
}

type Secret struct {
	ID        int32
	Hash      []byte
	Secret    []byte
	CreatedAt time.Time
}

type Service struct {
	ID             int32
	Name           string
	Address        string
	Protocol       string
	HostRegexp     string
	PathRegexp     string
	Price          int64
	Auth           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	AuthScheme     string
	PaymentLndhost string
	PaymentTlspath string
	PaymentMacpath string
}
