// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"
)

type LncSession struct {
	ID                 int32
	PassphraseWords    string
	PassphraseEntropy  []byte
	RemoteStaticPubKey []byte
	LocalStaticPrivKey []byte
	MailboxAddr        string
	CreatedAt          time.Time
	Expiry             sql.NullTime
	DevServer          bool
}

type Onion struct {
	PrivateKey []byte
	CreatedAt  time.Time
}

type Secret struct {
	ID        int32
	Hash      []byte
	Secret    []byte
	CreatedAt time.Time
}
