// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: mpp_charges.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteExpiredMPPConsumedCharges = `-- name: DeleteExpiredMPPConsumedCharges :execresult
DELETE FROM mpp_consumed_charges
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredMPPConsumedCharges(ctx context.Context, expiresAt time.Time) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteExpiredMPPConsumedCharges, expiresAt)
}

const getMPPConsumedCharge = `-- name: GetMPPConsumedCharge :one
SELECT id, payment_hash, challenge_id, expires_at, consumed_at
FROM mpp_consumed_charges
WHERE payment_hash = $1
`

func (q *Queries) GetMPPConsumedCharge(ctx context.Context, paymentHash []byte) (MppConsumedCharge, error) {
	row := q.db.QueryRowContext(ctx, getMPPConsumedCharge, paymentHash)
	var i MppConsumedCharge
	err := row.Scan(
		&i.ID,
		&i.PaymentHash,
		&i.ChallengeID,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const insertMPPConsumedCharge = `-- name: InsertMPPConsumedCharge :execresult
INSERT INTO mpp_consumed_charges (
    payment_hash, challenge_id, expires_at, consumed_at
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (payment_hash) DO NOTHING
`

type InsertMPPConsumedChargeParams struct {
	PaymentHash []byte
	ChallengeID string
	ExpiresAt   time.Time
	ConsumedAt  time.Time
}

func (q *Queries) InsertMPPConsumedCharge(ctx context.Context, arg InsertMPPConsumedChargeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertMPPConsumedCharge,
		arg.PaymentHash,
		arg.ChallengeID,
		arg.ExpiresAt,
		arg.ConsumedAt,
	)
}
