// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: mpp_sessions.sql

package sqlc

import (
	"context"
	"time"
)

const closeMPPSession = `-- name: CloseMPPSession :exec
UPDATE mpp_sessions
SET status = 'closed', updated_at = $1
WHERE session_id = $2 AND status = 'open'
`

type CloseMPPSessionParams struct {
	UpdatedAt time.Time
	SessionID string
}

func (q *Queries) CloseMPPSession(ctx context.Context, arg CloseMPPSessionParams) error {
	_, err := q.db.ExecContext(ctx, closeMPPSession, arg.UpdatedAt, arg.SessionID)
	return err
}

const getMPPSessionByID = `-- name: GetMPPSessionByID :one
SELECT id, session_id, payment_hash, deposit_sats, spent_sats, return_invoice, status, created_at, updated_at
FROM mpp_sessions
WHERE session_id = $1
`

func (q *Queries) GetMPPSessionByID(ctx context.Context, sessionID string) (MppSession, error) {
	row := q.db.QueryRowContext(ctx, getMPPSessionByID, sessionID)
	var i MppSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PaymentHash,
		&i.DepositSats,
		&i.SpentSats,
		&i.ReturnInvoice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMPPSession = `-- name: InsertMPPSession :one
INSERT INTO mpp_sessions (
    session_id, payment_hash, deposit_sats, spent_sats,
    return_invoice, status, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id
`

type InsertMPPSessionParams struct {
	SessionID     string
	PaymentHash   []byte
	DepositSats   int64
	SpentSats     int64
	ReturnInvoice string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) InsertMPPSession(ctx context.Context, arg InsertMPPSessionParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertMPPSession,
		arg.SessionID,
		arg.PaymentHash,
		arg.DepositSats,
		arg.SpentSats,
		arg.ReturnInvoice,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateMPPSessionDeposit = `-- name: UpdateMPPSessionDeposit :exec
UPDATE mpp_sessions
SET deposit_sats = deposit_sats + $1, updated_at = $2
WHERE session_id = $3 AND status = 'open'
`

type UpdateMPPSessionDepositParams struct {
	DepositSats int64
	UpdatedAt   time.Time
	SessionID   string
}

func (q *Queries) UpdateMPPSessionDeposit(ctx context.Context, arg UpdateMPPSessionDepositParams) error {
	_, err := q.db.ExecContext(ctx, updateMPPSessionDeposit, arg.DepositSats, arg.UpdatedAt, arg.SessionID)
	return err
}

const updateMPPSessionSpent = `-- name: UpdateMPPSessionSpent :exec
UPDATE mpp_sessions
SET spent_sats = spent_sats + $1, updated_at = $2
WHERE session_id = $3 AND status = 'open'
`

type UpdateMPPSessionSpentParams struct {
	SpentSats int64
	UpdatedAt time.Time
	SessionID string
}

func (q *Queries) UpdateMPPSessionSpent(ctx context.Context, arg UpdateMPPSessionSpentParams) error {
	_, err := q.db.ExecContext(ctx, updateMPPSessionSpent, arg.SpentSats, arg.UpdatedAt, arg.SessionID)
	return err
}
