// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package sqlc

import (
	"context"
	"time"
)

const deleteService = `-- name: DeleteService :execrows
DELETE FROM services
WHERE name = $1
`

func (q *Queries) DeleteService(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteService, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listServices = `-- name: ListServices :many
SELECT id, name, address, protocol, host_regexp, path_regexp, price, auth, created_at, updated_at
FROM services
ORDER BY name
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Protocol,
			&i.HostRegexp,
			&i.PathRegexp,
			&i.Price,
			&i.Auth,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertService = `-- name: UpsertService :exec
INSERT INTO services (
    name, address, protocol, host_regexp, path_regexp, price, auth,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT(name) DO UPDATE SET
    address = excluded.address,
    protocol = excluded.protocol,
    host_regexp = excluded.host_regexp,
    path_regexp = excluded.path_regexp,
    price = excluded.price,
    auth = excluded.auth,
    updated_at = excluded.updated_at
`

type UpsertServiceParams struct {
	Name       string
	Address    string
	Protocol   string
	HostRegexp string
	PathRegexp string
	Price      int64
	Auth       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) UpsertService(ctx context.Context, arg UpsertServiceParams) error {
	_, err := q.db.ExecContext(ctx, upsertService,
		arg.Name,
		arg.Address,
		arg.Protocol,
		arg.HostRegexp,
		arg.PathRegexp,
		arg.Price,
		arg.Auth,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
